version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: fortunespinner-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fortunespinner
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
      interval: 5s

  backend:
    image: golang:1.20-alpine
    container_name: fortunespinner-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - go_cache:/go/pkg/mod
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: fortunespinner
      PORT: 8080
      CGO_ENABLED: 0
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    command: go run main.go
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: fortunespinner-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm install && npm start"
    restart: unless-stopped

volumes:
  mysql_data:
  go_cache:
  node_modules: